# Base for frontend
FROM node:18-alpine AS base
WORKDIR /react-app
COPY react-app/package-lock.json react-app/package.json ./
RUN npm install
COPY react-app .

# development version run command
FROM base AS dev
ENTRYPOINT [ "npm" ]
CMD [ "run", "dev" ]


